package com.mycompany.enrollmentsystem;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ualfante
 */
public class StudentsForm extends javax.swing.JFrame {
    String stdid;
    public void showRecords(){
        DefaultTableModel tblmodel = (DefaultTableModel) studTable.getModel();
        tblmodel.setRowCount(0);
        EnrollmentSystem b = new EnrollmentSystem();
        b.DBConnect();
        
        String searchText = search.getText();
        if (searchText.equals("Search")) searchText = ""; // HOPEFULLY shows tables after saving
    
        
        try{
            String query = "select * from students where concat(studid, studname, studadd, studcrs, studgender, yrlvl) like '%" + searchText + "%'";
            b.rs = b.st.executeQuery(query);
            System.out.println("Success with sql!");  
            
            while (b.rs.next()){
                String i = b.rs.getString("studid");
                String c = b.rs.getString("studname");
                String d = b.rs.getString("studadd");
                String t = b.rs.getString("studcrs");
                String g = b.rs.getString("studgender");
                String y = b.rs.getString("yrlvl");
                String[] items = {i,c,d,t,g,y};
                tblmodel.addRow(items); //array
            }
        }catch (Exception ex){
            System.out.print("not Success with sql!");
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentsForm.class.getName());

    /**
     * Creates new form StudentsForm
     */
    public StudentsForm() {
        initComponents();
        studid.setEditable(false);     
        studgender.setEditable(true);
        showRecords();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel4 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        studTable = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        studid = new javax.swing.JTextField();
        studname = new javax.swing.JTextField();
        studadd = new javax.swing.JTextField();
        studcrs = new javax.swing.JTextField();
        studgender = new javax.swing.JTextField();
        yrlvl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enrollRecTable = new javax.swing.JTable();
        EnrollSubject = new javax.swing.JButton();
        DropSubject = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        open = new javax.swing.JMenu();
        subjects = new javax.swing.JMenuItem();
        teachers = new javax.swing.JMenuItem();
        Database = new javax.swing.JMenu();
        make1stSemDB = new javax.swing.JMenuItem();
        make2ndSemDB = new javax.swing.JMenuItem();
        makeSummerDB = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel4.setText("jLabel4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Course", "Gender", "Year Level"
            }
        ));
        studTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(studTable);

        search.setText("Search");
        search.setToolTipText("");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        search.addActionListener(this::searchActionPerformed);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("STUDENT INFORMATION SYSTEM");

        studid.setEditable(false);
        studid.addActionListener(this::studidActionPerformed);

        studname.addActionListener(this::studnameActionPerformed);

        studgender.setEditable(false);
        studgender.addActionListener(this::studgenderActionPerformed);

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        saveBtn.setText("Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        editBtn.setText("Edit");
        editBtn.addActionListener(this::editBtnActionPerformed);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        jLabel5.setText("Address");

        jLabel6.setText("Course");

        jLabel7.setText("Gender");

        jLabel8.setText("Year LVL");

        enrollRecTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sbject ID", "Subject code", "Subject description", "Subject units", "Subject Sched"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enrollRecTable);

        EnrollSubject.setText("Enroll Subject");
        EnrollSubject.addActionListener(this::EnrollSubjectActionPerformed);

        DropSubject.setText("Drop Subject");
        DropSubject.addActionListener(this::DropSubjectActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Enrolled Subjects");

        open.setText("open");

        subjects.setText("subjects");
        subjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectsMouseClicked(evt);
            }
        });
        subjects.addActionListener(this::subjectsActionPerformed);
        open.add(subjects);

        teachers.setText("teachers");
        teachers.addActionListener(this::teachersActionPerformed);
        open.add(teachers);

        jMenuBar1.add(open);

        Database.setText("Database");
        Database.addActionListener(this::DatabaseActionPerformed);

        make1stSemDB.setText("1st sem");
        make1stSemDB.addActionListener(this::make1stSemDBActionPerformed);
        Database.add(make1stSemDB);

        make2ndSemDB.setText("2nd sem");
        make2ndSemDB.addActionListener(this::make2ndSemDBActionPerformed);
        Database.add(make2ndSemDB);

        makeSummerDB.setText("Summer");
        makeSummerDB.addActionListener(this::makeSummerDBActionPerformed);
        Database.add(makeSummerDB);

        jMenuBar1.add(Database);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yrlvl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studgender, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studcrs, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studadd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EnrollSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DropSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(saveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteBtn))
                            .addComponent(jLabel1))
                        .addGap(659, 659, 659))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studcrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yrlvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn))
                .addGap(38, 38, 38)
                .addComponent(EnrollSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DropSubject)
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        showRecords();
    }//GEN-LAST:event_searchKeyPressed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        if (search.getText().equals("Search"))search.setText("");
    }//GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        if (search.getText().trim().isEmpty())search.setText("Search");
    }//GEN-LAST:event_searchFocusLost

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Students c = new Students();
            c.newstudent(
                studname.getText(),
                studadd.getText(),
                studcrs.getText(),
                studgender.getText(),
                yrlvl.getText()
            );
            showRecords();
            clearFields();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void studnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studnameActionPerformed

    private void studidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studidActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if (studid.getText().trim().isEmpty()) {
            messagebox("select a student to edit first", "Edit");
            return;
        }
        Students c = new Students();
        c.updateStudent(Integer.parseInt(studid.getText()), studname.getText(), studadd.getText(), studcrs.getText(), yrlvl.getText());
        showRecords();
        clearFields();
    }//GEN-LAST:event_editBtnActionPerformed
     private void messagebox(String msg, String titlebar){
        JOptionPane.showMessageDialog(null,msg,titlebar,JOptionPane.INFORMATION_MESSAGE);   
    } 
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (studid.getText().trim().isEmpty()) {
            messagebox("select a student to delete first", "Delete");
            return;
        }
        
        Students c = new Students();
        c.deleteStudent(Integer.parseInt(studid.getText()));
        showRecords();
        clearFields();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void studTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studTableMouseClicked
        studgender.setEditable(false);
        studid.setEditable(false);
        int[] selectRow = studTable.getSelectedRows();
        if (selectRow.length > 0) {
            stdid = (String) studTable.getValueAt(selectRow[0], 0);
            studid.setText(stdid);

            // Lock ID so it cannot be modified
            studid.setEditable(false);

            String sname = (String) studTable.getValueAt(selectRow[0], 1);
            studname.setText(sname);
            String sadd = (String) studTable.getValueAt(selectRow[0], 2);
            studadd.setText(sadd);
            String scrs = (String) studTable.getValueAt(selectRow[0], 3);
            studcrs.setText(scrs);
            String sgender = (String) studTable.getValueAt(selectRow[0], 4);
            studgender.setText(sgender);
            String syr = (String) studTable.getValueAt(selectRow[0], 5);
            yrlvl.setText(syr);
            ShowEnrollRec();
        }
    }//GEN-LAST:event_studTableMouseClicked
    private void ShowEnrollRec(){
        DefaultTableModel tblmodel = (DefaultTableModel) enrollRecTable.getModel();
        tblmodel.setRowCount(0);
        EnrollmentSystem b = new EnrollmentSystem();
        b.DBConnect();
        
        String searchText = search.getText();
        if (searchText.equals("Search")) searchText = ""; // HOPEFULLY shows tables after saving
    
        
        try{
            String query = "select * from subjects where subjid in (select subjid from enroll where studid ='" + stdid + "')";
            b.rs = b.st.executeQuery(query);
            System.out.println("Success with sql!");  
            
            while (b.rs.next()){
                String i = b.rs.getString("subjid");
                String c = b.rs.getString("subjcode");
                String d = b.rs.getString("subjdesc");
                String t = b.rs.getString("subjunits");
                String g = b.rs.getString("subjsched");
                String[] items = {i,c,d,t,g};
                tblmodel.addRow(items); //array
            }
        }catch (Exception ex){
            System.out.print("not Success with sql!");
        }
    }   
    public static int okcancel(String theMessage){
        int result = JOptionPane.showConfirmDialog((Component) null, theMessage, "alert", JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    private void subjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectsActionPerformed
        SubjectsFrame a = new SubjectsFrame();
        a.setVisible(true);
    }//GEN-LAST:event_subjectsActionPerformed

    private void subjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectsMouseClicked
        SubjectsFrame a = new SubjectsFrame();
        a.setVisible(true);
    }//GEN-LAST:event_subjectsMouseClicked

    private void teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersActionPerformed
       TeachersFrame z = new TeachersFrame();
       z.setVisible(true);
    }//GEN-LAST:event_teachersActionPerformed

    private void DatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatabaseActionPerformed

    private void EnrollSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollSubjectActionPerformed
        //checks
        if (stdid == null || stdid.trim().isEmpty()) {
            messagebox("Please select a student from the table first!", "Enroll");
            return;
        }
        Enroll a = new Enroll();
        if (a.getSubjid() == 0) {
            messagebox("Please select a subject from the Subjects window first!", "Enroll");
            return;
        }
        
        int i = okcancel("Enroll Student ID:" + stdid + " to subject ID:"  + a.getSubjid() + "?");
        if(i==0){
            messagebox("Enrolled " + stdid, "enroll");
            a.enrollStud(Integer.parseInt(stdid));
            ShowEnrollRec();
        }else{
            messagebox("Cancel Enroll" + stdid, "enroll");
        }
    }//GEN-LAST:event_EnrollSubjectActionPerformed

    private void studgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studgenderActionPerformed

    private void DropSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropSubjectActionPerformed
         if (stdid == null || stdid.trim().isEmpty()) {
            messagebox("Please select a student from the table first!", "Drop Subject");
            return;
        }
        int row = enrollRecTable.getSelectedRow();
        if (row < 0) {
            messagebox("Please select an enrolled subject from the table to drop!", "Drop Subject");
            return;
        }
        int subjectToDrop = Integer.parseInt(enrollRecTable.getValueAt(row, 0).toString());
        int i = okcancel("Are you sure you want to drop Student ID: " + stdid + " from Subject ID: " + subjectToDrop + "?");
        if (i == 0) {
            Enroll a = new Enroll();
            String msg = a.dropStud(Integer.parseInt(stdid), subjectToDrop);
            messagebox(msg, "Drop Subject");
            ShowEnrollRec(); // Refresh table so the dropped subject disappears!
        } else {
            messagebox("Drop cancelled.", "Drop Subject");
        }
    }//GEN-LAST:event_DropSubjectActionPerformed

    private void make1stSemDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make1stSemDBActionPerformed
        EnrollmentSystem a = new EnrollmentSystem();
        messagebox(a.newdb("1st"), "success");
    }//GEN-LAST:event_make1stSemDBActionPerformed

    private void make2ndSemDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make2ndSemDBActionPerformed
        EnrollmentSystem a = new EnrollmentSystem();
        messagebox(a.newdb("2nd"), "success");
    }//GEN-LAST:event_make2ndSemDBActionPerformed

    private void makeSummerDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeSummerDBActionPerformed
        EnrollmentSystem a = new EnrollmentSystem();
        messagebox(a.newdb("Summer"), "success");
    }//GEN-LAST:event_makeSummerDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentsForm().setVisible(true));
    }
    
    private void clearFields() {
    studid.setText("");
    studname.setText("");
    studadd.setText("");
    studcrs.setText("");
    studgender.setText("");
    yrlvl.setText("");
    
    // Unlock the ID field for entering new student records
    studid.setEditable(false);
    studgender.setEditable(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Database;
    private javax.swing.JButton DropSubject;
    private javax.swing.JButton EnrollSubject;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTable enrollRecTable;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem make1stSemDB;
    private javax.swing.JMenuItem make2ndSemDB;
    private javax.swing.JMenuItem makeSummerDB;
    private javax.swing.JMenu open;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField search;
    private javax.swing.JTable studTable;
    private javax.swing.JTextField studadd;
    private javax.swing.JTextField studcrs;
    private javax.swing.JTextField studgender;
    private javax.swing.JTextField studid;
    private javax.swing.JTextField studname;
    private javax.swing.JMenuItem subjects;
    private javax.swing.JMenuItem teachers;
    private javax.swing.JTextField yrlvl;
    // End of variables declaration//GEN-END:variables
}
