/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.enrollmentsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ualfante
 */
public class SubjectsFrame extends javax.swing.JFrame {
    
    public void showRecords(){
        DefaultTableModel tblmodel = (DefaultTableModel) subjTable.getModel();
        tblmodel.setRowCount(0);
        EnrollmentSystem b = new EnrollmentSystem();
        b.DBConnect();
        
        String searchText = search.getText();
        if (searchText.equals("Search")) searchText = ""; // HOPEFULLY shows tables after saving
    
        
        try{
            String query = "select * from subjects where concat_ws(subjid, subjcode, subjdesc, subjunits, subjsched) like '%" + searchText + "%'";
            b.rs = b.st.executeQuery(query);
            System.out.println("Success with sql!");  
            
            while (b.rs.next()){
                String i = b.rs.getString("subjid");
                String c = b.rs.getString("subjcode");
                String d = b.rs.getString("subjdesc");
                String t = b.rs.getString("subjunits");
                String g = b.rs.getString("subjsched");
                String[] items = {i,c,d,t,g};
                tblmodel.addRow(items); //array
            }
        }catch (Exception ex){
            System.out.print("not Success with sql!");
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubjectsFrame.class.getName());

    /**
     * Creates new form SubjectsFrame
     */
    public SubjectsFrame() {
        initComponents();
        showRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        subjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        subjid = new javax.swing.JTextField();
        subjcode = new javax.swing.JTextField();
        subjdesc = new javax.swing.JTextField();
        subjunit = new javax.swing.JTextField();
        subjsched = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        open = new javax.swing.JMenu();
        Students = new javax.swing.JCheckBoxMenuItem();
        Teachers = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Subject ID", "Code", "Description", "Units", "Sched"
            }
        ));
        subjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjTable);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("subjects");

        subjid.addActionListener(this::subjidActionPerformed);

        subjcode.setToolTipText("");

        subjsched.addActionListener(this::subjschedActionPerformed);

        jLabel2.setText("Subject ID");

        jLabel3.setText("Subject Code");

        jLabel4.setText("Subject Desc.");

        jLabel5.setText("Subject Unit");

        jLabel6.setText("Subject Sched");

        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(this::SaveActionPerformed);

        Edit.setText("Edit");
        Edit.addActionListener(this::EditActionPerformed);

        Delete.setText("Delete");
        Delete.addActionListener(this::DeleteActionPerformed);

        open.setText("open");

        Students.setSelected(true);
        Students.setText("Students");
        Students.addActionListener(this::StudentsActionPerformed);
        open.add(Students);

        Teachers.setSelected(true);
        Teachers.setText("Teachers");
        Teachers.addActionListener(this::TeachersActionPerformed);
        open.add(Teachers);

        jMenuBar1.add(open);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(268, 268, 268))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(subjid)
                            .addComponent(subjcode)
                            .addComponent(subjsched)
                            .addComponent(subjunit)
                            .addComponent(subjdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delete))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjsched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Edit)
                    .addComponent(Delete))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjidActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        showRecords();
    }//GEN-LAST:event_searchKeyPressed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        if (search.getText().equals("Search"))search.setText("");
    }//GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        if (search.getText().trim().isEmpty())search.setText("Search");
    }//GEN-LAST:event_searchFocusLost

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Subjects c = new Subjects();
        c.newsubject(Integer.parseInt(subjid.getText()), subjcode.getText(),subjdesc.getText(),subjunit.getText(),subjsched.getText());
        showRecords();
    }//GEN-LAST:event_SaveActionPerformed

    private void subjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjTableMouseClicked
        int[] selectRow = subjTable.getSelectedRows();
        if (selectRow.length > 0) {
            String stdid = (String) subjTable.getValueAt(selectRow[0], 0);
            subjid.setText(stdid);

            // Lock ID so it cannot be modified
            subjid.setEditable(false);

            String sbcode = (String) subjTable.getValueAt(selectRow[0], 1);
            subjcode.setText(sbcode);
            String sbdesc = (String) subjTable.getValueAt(selectRow[0], 2);
            subjdesc.setText(sbdesc);
            String sbunit = (String) subjTable.getValueAt(selectRow[0], 3);
            subjunit.setText(sbunit);
            String sbsched = (String) subjTable.getValueAt(selectRow[0], 4);
            subjsched.setText(sbsched);
        }
        
    }//GEN-LAST:event_subjTableMouseClicked

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        if (subjid.getText().trim().isEmpty()) {
            messagebox("select a student to edit first", "Edit");
            return;
        }
        Subjects c = new Subjects();
        c.updateSubjects(Integer.parseInt(subjid.getText()), subjcode.getText(), subjdesc.getText(), subjunit.getText(), subjsched.getText());
        showRecords();
        clearFields();
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if (subjid.getText().trim().isEmpty()) {
            messagebox("select a student to delete first", "Delete");
            return;
        }
        
        Subjects c = new Subjects();
        c.deleteSubjects(Integer.parseInt(subjid.getText()));
        showRecords();
        clearFields();
    }//GEN-LAST:event_DeleteActionPerformed

    private void subjschedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjschedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjschedActionPerformed

    private void StudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsActionPerformed
        StudentsForm a = new StudentsForm();
        a.setVisible(true);
    }//GEN-LAST:event_StudentsActionPerformed

    private void TeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersActionPerformed
       TeachersFrame z = new TeachersFrame();
       z.setVisible(true);        
    }//GEN-LAST:event_TeachersActionPerformed
     
    private void messagebox(String msg, String titlebar){
        JOptionPane.showMessageDialog(null,msg,titlebar,JOptionPane.INFORMATION_MESSAGE);   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SubjectsFrame().setVisible(true));
    }
    
    private void clearFields() {
    subjid.setText("");
    subjcode.setText("");
    subjdesc.setText("");
    subjunit.setText("");
    subjsched.setText("");
    subjid.setEditable(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Save;
    private javax.swing.JCheckBoxMenuItem Students;
    private javax.swing.JCheckBoxMenuItem Teachers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu open;
    private javax.swing.JTextField search;
    private javax.swing.JTable subjTable;
    private javax.swing.JTextField subjcode;
    private javax.swing.JTextField subjdesc;
    private javax.swing.JTextField subjid;
    private javax.swing.JTextField subjsched;
    private javax.swing.JTextField subjunit;
    // End of variables declaration//GEN-END:variables
}
