/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.enrollmentsystem;

import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author euri
 */
public class TeachersFrame extends javax.swing.JFrame {
    
        public void showRecords(){
        DefaultTableModel tblmodel = (DefaultTableModel) teacherTable.getModel();
        tblmodel.setRowCount(0);
        EnrollmentSystem b = new EnrollmentSystem();
        b.DBConnect();
        
        String searchText = search.getText();
        if (searchText.equals("Search")) searchText = ""; // HOPEFULLY shows tables after saving
    
        
        try{
            String query = "select * from teachers where concat_ws(tid, tname, tdept, tcontact) like '%" + searchText + "%'";
            b.rs = b.st.executeQuery(query);
            System.out.println("Success with sql!");  
            
            while (b.rs.next()){
                String i = b.rs.getString("tid");
                String c = b.rs.getString("tname");
                String d = b.rs.getString("tdept");
                String t = b.rs.getString("tcontact");
                String[] items = {i,c,d,t};
                tblmodel.addRow(items); //array
            }
        }catch (Exception ex){
            System.out.print("not Success with sql!");
        }
    }
    
    private void ShowAssignRec(){
        DefaultTableModel tblmodel = (DefaultTableModel) assignedSubjTable.getModel();
        tblmodel.setRowCount(0);
        EnrollmentSystem b = new EnrollmentSystem();
        b.DBConnect();
        
        try{
            String query = "select * from subjects where subjid in (select SubjID from assign where TID ='" + tid.getText() + "')";
            b.rs = b.st.executeQuery(query);
            System.out.println("Success with sql!");  
            
            while (b.rs.next()){
                String i = b.rs.getString("subjid");
                String c = b.rs.getString("subjcode");
                String d = b.rs.getString("subjdesc");
                String t = b.rs.getString("subjunits");
                String g = b.rs.getString("subjsched");
                String[] items = {i,c,d,t,g};
                tblmodel.addRow(items);
            }
        }catch (Exception ex){
            System.out.print("not Success with sql!");
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeachersFrame.class.getName());

    /**
     * Creates new form TeachersFrame
     */
    public TeachersFrame() {
        initComponents();
        tid.setEditable(false);
        showRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        tdept = new javax.swing.JTextField();
        tcontact = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        assignedSubjTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Assign = new javax.swing.JButton();
        Unassign = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        open = new javax.swing.JMenu();
        Students = new javax.swing.JCheckBoxMenuItem();
        Subjects = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(825, 537));

        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Teacher ID", "Teacher Name", "Teacher Dept", "Teacher contact"
            }
        ));
        teacherTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(teacherTable);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Teachers");

        tid.setEditable(false);
        tid.addActionListener(this::tidActionPerformed);

        tdept.addActionListener(this::tdeptActionPerformed);

        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });

        jLabel2.setText("Teacher ID");

        jLabel3.setText("Teacher Name");

        jLabel4.setText("Teacher Dept");

        jLabel5.setText("Teacher Contact");

        Save.setText("Save");
        Save.addActionListener(this::SaveActionPerformed);

        Edit.setText("Edit");
        Edit.addActionListener(this::EditActionPerformed);

        Delete.setText("Delete");
        Delete.addActionListener(this::DeleteActionPerformed);

        assignedSubjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SubjID", "SubjCode", "SubjDesc", "SubjUnits", "SubjSched"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(assignedSubjTable);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Assigned Subjects");

        Assign.setText("Assign");
        Assign.addActionListener(this::AssignActionPerformed);

        Unassign.setText("Unassign");
        Unassign.addActionListener(this::UnassignActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(429, 429, 429))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tcontact)
                                    .addComponent(tdept)
                                    .addComponent(tname)
                                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Assign, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Unassign, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Save)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Edit)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Delete))
                                .addComponent(jScrollPane2)))
                        .addContainerGap(35, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Edit)
                    .addComponent(Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Assign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Unassign)))
                .addGap(44, 44, 44))
        );

        open.setText("open");

        Students.setSelected(true);
        Students.setText("Students");
        Students.addActionListener(this::StudentsActionPerformed);
        open.add(Students);

        Subjects.setSelected(true);
        Subjects.setText("Subjects");
        Subjects.addActionListener(this::SubjectsActionPerformed);
        open.add(Subjects);

        jMenuBar1.add(open);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void tdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdeptActionPerformed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        if (search.getText().equals("Search"))search.setText("");
    }//GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        if (search.getText().trim().isEmpty())search.setText("Search");
    }//GEN-LAST:event_searchFocusLost

    private void teacherTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTableMouseClicked
        int[] selectRow = teacherTable.getSelectedRows();
        if (selectRow.length > 0) {
            String teachid = (String) teacherTable.getValueAt(selectRow[0], 0);
            tid.setText(teachid);

            // Lock ID so it cannot be modified
            tid.setEditable(false);

            String teachname = (String) teacherTable.getValueAt(selectRow[0], 1);
            tname.setText(teachname);
            String teachdept = (String) teacherTable.getValueAt(selectRow[0], 2);
            tdept.setText(teachdept);
            String teachcontact = (String) teacherTable.getValueAt(selectRow[0], 3);
            tcontact.setText(teachcontact);
            ShowAssignRec();
        }
    }//GEN-LAST:event_teacherTableMouseClicked

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Teacher c = new Teacher();
        c.newteacher(tname.getText(), tdept.getText(), tcontact.getText());
        showRecords();        
        clearFields();       
    }//GEN-LAST:event_SaveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if (tid.getText().trim().isEmpty()) {
            messagebox("select a student to delete first", "Delete");
            return;
        }
        
        Teacher c = new Teacher();
        c.deleteteacher(Integer.parseInt(tid.getText()));
        showRecords();
        clearFields(); 
    }//GEN-LAST:event_DeleteActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        if (tid.getText().trim().isEmpty()) {
            messagebox("select a student to edit first", "Edit");
            return;
        }
        Teacher c = new Teacher();
        c.updateteacher(Integer.parseInt(tid.getText()), tname.getText(), tdept.getText(), tcontact.getText());
        showRecords();
        clearFields();      
    }//GEN-LAST:event_EditActionPerformed

    private void SubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectsActionPerformed
        SubjectsFrame a = new SubjectsFrame();
        a.setVisible(true);
    }//GEN-LAST:event_SubjectsActionPerformed

    private void StudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsActionPerformed
        StudentsForm a = new StudentsForm();
        a.setVisible(true);
    }//GEN-LAST:event_StudentsActionPerformed

    private void AssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignActionPerformed
        if (tid.getText().trim().isEmpty()) {
            messagebox("Please select a teacher from the table first!", "Assign");
            return;
        }
        
        Assign a = new Assign();
        if (a.getSubjid() == 0) {
            messagebox("Please select a subject from the Subjects window first!", "Assign");
            return;
        }
        
        int i = okcancel("Assign Teacher ID: " + tid.getText() + " to Subject ID: " + a.getSubjid() + "?");
        if (i == 0) {
            String msg = a.assignTeacher(Integer.parseInt(tid.getText()));
            messagebox(msg, "Assign");
            ShowAssignRec(); // Refresh table immediately!
        } else {
            messagebox("Assign cancelled.", "Assign");
        }
    }//GEN-LAST:event_AssignActionPerformed
    public static int okcancel(String theMessage){
        int result = JOptionPane.showConfirmDialog((Component) null, theMessage, "alert", JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    private void UnassignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnassignActionPerformed
         if (tid.getText().trim().isEmpty()) {
            messagebox("Please select a teacher from the table first!", "Drop Subject");
            return;
        }
        int row = assignedSubjTable.getSelectedRow();
        if (row < 0) {
            messagebox("Please select an assigned subject from the table to drop!", "Drop Subject");
            return;
        }
        int subjectToDrop = Integer.parseInt(assignedSubjTable.getValueAt(row, 0).toString());
        int i = okcancel("Are you sure you want to drop Teacher ID: " + tid.getText() + " from Subject ID: " + subjectToDrop + "?");
        if (i == 0) {
            Assign a = new Assign();
            String msg = a.unassignTeacher(Integer.parseInt(tid.getText()), subjectToDrop);
            messagebox(msg, "Drop Subject");
            ShowAssignRec(); // Refresh table immediately!
        } else {
            messagebox("Drop cancelled.", "Drop Subject");
        }
    }//GEN-LAST:event_UnassignActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void clearFields() {
    tid.setText("");
    tname.setText("");
    tdept.setText("");
    tcontact.setText("");
    
    // Unlock the ID field for entering new teacher records
    tid.setEditable(false);
}
    
    private void messagebox(String msg, String titlebar){
        JOptionPane.showMessageDialog(null,msg,titlebar,JOptionPane.INFORMATION_MESSAGE);   
    }
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TeachersFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assign;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Save;
    private javax.swing.JCheckBoxMenuItem Students;
    private javax.swing.JCheckBoxMenuItem Subjects;
    private javax.swing.JButton Unassign;
    private javax.swing.JTable assignedSubjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu open;
    private javax.swing.JTextField search;
    private javax.swing.JTextField tcontact;
    private javax.swing.JTextField tdept;
    private javax.swing.JTable teacherTable;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tname;
    // End of variables declaration//GEN-END:variables
}
